// Every fixed string on the printed anaesthesia record, in both languages.
//
// These are not app chrome — they are the wording of a document that goes into
// a patient's notes, so they live as one paired table rather than scattered
// through the sheet markup: an English label with no Bulgarian twin is visible
// here and invisible anywhere else.

export const LABELS = {
  en: {
    record: "ANAESTHESIA RECORD", prepost: "PRE- & POST-OPERATIVE",
    intraopTt: "INTRAOPERATIVE TIMETABLE", preopAssessment: "PREOPERATIVE ASSESSMENT", postopRecoveryLbl: "POSTOPERATIVE RECOVERY",
    patientName: "Patient name", idFile: "ID / File №", nameSig: "name & signature",
    histCom: "History & comorbidities", investigations: "Investigations", airwayAssessment: "Airway assessment", anthropometry: "Anthropometry",
    // A draw with no recorded time. Its own group rather than folded into the
    // first dated one -- when it was taken is the point of grouping at all.
    undatedDraw: "Time not recorded",
    // The page is a fixed A4 box that clips rather than continuing, so a sheet
    // that could not fit everything says how much it left behind.
    labsOmitted: (results: number, draws: number) =>
      `+${results} earlier result${results === 1 ? "" : "s"} from ${draws} earlier draw${draws === 1 ? "" : "s"} — see the record`,
    aldreteTotalLbl: "Aldrete total", readyDischarge: "Ready for discharge", recoveryObs: "Recovery observations",
    footerLine: "LOSPOR personal case log · Not a clinical record · No patient identifiers stored — identity fields filled by hand after printing",
    generatedLbl: "Generated",
    printCase: "Print case", notNow: "Not now",
    edit: "Edit:", preopShort: "Preop", intraopShort: "Intraop", postopShort: "Postop", unfinalize: "Unfinalize",
    closing: "Closing…", closeNow: "Close Now",
    finalizeMissingTechnique: "No anaesthesia technique recorded", finalizeMissingPostop: "Post-op record not completed",
    finalizeMissingAldrete: "Aldrete score missing", finalizeMissingDisposition: "Patient disposition not recorded",
    finalizeMissingIntraop: "Intraop record not started", finalizeMissingPreop: "Pre-op assessment missing",
    finalizeInvalidTimes: "End time is before start time", finalizeFailed: "Could not finalize — check all required fields are complete.",
    nkda: "NKDA", ivAccess: "IV access", monitoringShort: "Monitoring",
    screenDisclaimer: "LOSPOR — Personal anaesthetic case log. Not a clinical record. Patient identifiers must not be added. © 2026 Kaloyan Dzhunov · AGPL-3.0",
    printPromptTitle: "Case finished",
    printPromptText: "The case is closed and flagged as finished. Print the two-page anaesthesia record now?",
    protocol: "ANAESTHESIA PROTOCOL", preoppost: "Preoperative & Postoperative Assessment",
    staff: "Staff", patient: "Patient", anaesthesia: "Anaesthesia", monitoring: "Monitoring",
    vascular: "Vascular Access", premed: "Premedication", drugTotals: "Drug / agent totals", drugLog: "Drug administration log", totalsLbl: "Totals", fluidBal: "Fluid balance", notes: "Intraop notes",
    anaesthesiologist: "Anaesthesiologist", surgeon: "Surgeon", nurse: "Nurse", duration: "Duration",
    diagnosis: "Diagnosis", procedure: "Planned Procedure", heightWeight: "Height / Weight",
    technique: "Technique", airway: "Airway", tools: "Tools", ventilation: "Ventilation",
    agent: "Agent", position: "Position",
    cryst: "Cryst.", colloid: "Colloid", blood: "Blood", urine: "Urine",
    riskScores: "Risk Scores", preVitals: "Preoperative Vitals", comorbidities: "Comorbidities",
    medications: "Medications", allergies: "Allergies", lab: "Laboratory",
    mouthOpening: "Mouth opening", thyromental: "Thyromental dist.", neckMobility: "Neck mobility",
    clGrade: "C-L grade", bp: "BP", hr: "HR", temp: "Temp", rr: "RR",
    postopRecovery: "Postoperative Recovery", total: "TOTAL", ready: "Ready",
    monitor: "Monitor", continueStr: "Continue", recovery: "Recovery",
    disposition: "Disposition", handover: "Handover",
    temperature: "Temperature", painNRS: "Pain NRS", ponv: "PONV",
    sigAnest: "Anaesthesiologist", sigNurse: "Anaesthesia nurse", sigSurg: "Surgeon",
    page1: "Page 1 of 2", page2: "Page 2 of 2", confidential: "Confidential",
    gdprNote: "GDPR: Patient-identifiable data — store securely. Anonymised record in LOSPOR.",
    reviewNote: "Review the two-page protocol below, then print or save as PDF.",
    privacyNote: "Patient name and ID are entered at print time only — they are never uploaded or stored.",
    printBtn: "🖨 Print / Save as PDF",
    warningTitle: "Before you print",
    warningText: "Once the case record has been finalised, any changes will require reopening the case again. Make sure all information is accurate before generating the protocol.",
    goBack: "Go back", continuePrint: "Continue to print",
    patientDialogTitle: "Patient identity for protocol",
    patientDialogNote: "These details are not stored in LOSPOR — only printed on the document.",
    lastNamePlaceholder: "Last name", firstNamePlaceholder: "First name", idPlaceholder: "File / ID number (optional)",
    cancel: "Cancel",
    noDrugs: "No drugs recorded", evening: "Evening", morning: "Morning",
    latexAllergy: "⚠ Latex allergy", familyHistory: "⚠ Family anaesthesia history",
    // The anaesthetic history has its own sub-heading rather than trailing the
    // allergy list, where a bold red "Malignant hyperthermia history" read as
    // an allergy entry.
    anaestheticHistory: "Anaesthetic history",
    malignantHyperthermia: "⚠ Malignant hyperthermia history",
    unexplainedAnaesthesiaComplications: "⚠ Unexplainable complications during anaesthesia",
    anticipatedDifficultAirway: "⚠ Anticipated difficult airway",
    difficultAirway: "⚠ Difficult airway history",
    loadingCase: "Loading case summary…", loadFailed: "Failed to load case data.",
    unfinalizeFailed: "Could not reopen the case. Please try again.",
  },
  bg: {
    record: "АНЕСТЕЗИОЛОГИЧЕН ПРОТОКОЛ", prepost: "ПРЕД- И СЛЕДОПЕРАТИВНА ОЦЕНКА",
    intraopTt: "ИНТРАОПЕРАТИВНА ТАБЛИЦА", preopAssessment: "ПРЕДОПЕРАТИВНА ОЦЕНКА", postopRecoveryLbl: "ПОСТОПЕРАТИВНО ВЪЗСТАНОВЯВАНЕ",
    patientName: "Име на пациента", idFile: "ИЗ / Номер", nameSig: "име и подпис",
    histCom: "Анамнеза и придружаващи заболявания", investigations: "Изследвания", airwayAssessment: "Оценка на дихателния път", anthropometry: "Антропометрия",
    undatedDraw: "Часът не е записан",
    labsOmitted: (results: number, draws: number) =>
      `+${results} по-ранни резултата от ${draws} по-ранни вземания — вижте записа`,
    aldreteTotalLbl: "Общо Aldrete", readyDischarge: "Готов за извеждане", recoveryObs: "Наблюдения при възстановяване",
    footerLine: "LOSPOR личен журнал на случаи · Не е клиничен документ · Не се съхраняват лични данни — полетата за самоличност се попълват на ръка след печат",
    generatedLbl: "Генериран",
    printCase: "Печат на случая", notNow: "Не сега",
    edit: "Редакция:", preopShort: "Предоп.", intraopShort: "Интраоп.", postopShort: "Следоп.", unfinalize: "Отмени финализирането",
    closing: "Затваряне…", closeNow: "Затвори сега",
    finalizeMissingTechnique: "Няма записана анестезиологична техника", finalizeMissingPostop: "Следоперативният запис не е завършен",
    finalizeMissingAldrete: "Липсва оценка по Aldrete", finalizeMissingDisposition: "Не е записано къде е насочен пациентът",
    finalizeMissingIntraop: "Интраоперативният запис не е започнат", finalizeMissingPreop: "Липсва предоперативна оценка",
    finalizeInvalidTimes: "Крайният час е преди началния", finalizeFailed: "Случаят не може да се финализира — проверете всички задължителни полета.",
    nkda: "Без известни лекарствени алергии", ivAccess: "Венозен достъп", monitoringShort: "Мониторинг",
    screenDisclaimer: "LOSPOR — Личен анестезиологичен журнал. Не е клиничен документ. Не добавяйте идентификатори на пациента. © 2026 Kaloyan Dzhunov · AGPL-3.0",
    printPromptTitle: "Случаят е приключен",
    printPromptText: "Случаят е затворен и отбелязан като приключен. Да се отпечата ли двустраничният анестезиологичен протокол сега?",
    protocol: "АНЕСТЕЗИОЛОГИЧЕН ПРОТОКОЛ", preoppost: "Предоперативна и следоперативна оценка",
    staff: "Персонал", patient: "Пациент", anaesthesia: "Анестезия", monitoring: "Мониторинг",
    vascular: "Съдов достъп", premed: "Премедикация", drugTotals: "Медикаменти / агенти", drugLog: "Дневник на медикаментите", totalsLbl: "Общо", fluidBal: "Баланс на течности", notes: "Интраоп. бележки",
    anaesthesiologist: "Анестезиолог", surgeon: "Хирург", nurse: "Мед. сестра", duration: "Продължителност",
    diagnosis: "Диагноза", procedure: "Интервенция", heightWeight: "Ръст / Тегло",
    technique: "Техника", airway: "Дихателен път", tools: "Инструменти", ventilation: "Вентилация",
    agent: "Агент", position: "Положение",
    cryst: "Крист.", colloid: "Колоид", blood: "Кръв", urine: "Диуреза",
    riskScores: "Скали за оценка на риска", preVitals: "Предоп. жизнени показатели", comorbidities: "Придружаващи заболявания",
    medications: "Медикаменти", allergies: "Алергии", lab: "Лабораторни изследвания",
    mouthOpening: "Разстояние между резците", thyromental: "Тиромандибулярно разст.", neckMobility: "Подвижност на шията",
    clGrade: "C-L степен", bp: "АН", hr: "СЧ", temp: "Темп.", rr: "ДЧ",
    postopRecovery: "Постоперативно състояние", total: "ОБЩО", ready: "Готов",
    monitor: "Наблюдение", continueStr: "Продължи", recovery: "Състояние при извеждане от операционната зала",
    disposition: "Извежда се към", handover: "Препоръки за постоперативния период",
    temperature: "Температура", painNRS: "Болкова скала NRS", ponv: "ПОНВ",
    sigAnest: "Анестезиолог", sigNurse: "Анестезиологична мед. сестра", sigSurg: "Хирург",
    page1: "Страница 1 от 2", page2: "Страница 2 от 2", confidential: "Поверително",
    gdprNote: "GDPR: Документът съдържа лични данни — съхранявайте в историята. Анонимен запис в LOSPOR.",
    reviewNote: "Прегледайте протокола по-долу, след което отпечатайте или запазете като PDF.",
    privacyNote: "Имената и ИД на пациента се въвеждат само при печат — никога не се качват или съхраняват.",
    printBtn: "🖨 Печат / Запази като PDF",
    warningTitle: "Преди да отпечатате",
    warningText: "След финализиране на случая промените изискват повторното му отваряне. Уверете се, че всички данни са верни преди генерирането на протокола.",
    goBack: "Назад", continuePrint: "Продължи към печат",
    patientDialogTitle: "Самоличност на пациента за протокола",
    patientDialogNote: "Тези данни не се съхраняват в LOSPOR — само се отпечатват на документа.",
    lastNamePlaceholder: "Фамилия", firstNamePlaceholder: "Собствено", idPlaceholder: "ИЗ / Идентификатор (незадължително)",
    cancel: "Отказ",
    noDrugs: "Без записани медикаменти", evening: "Вечер", morning: "Сутрин",
    latexAllergy: "⚠ Алергия към латекс", familyHistory: "⚠ Фамилна анестезиологична история",
    anaestheticHistory: "Анестезиологична анамнеза",
    malignantHyperthermia: "⚠ Анамнеза за малигнена хипертермия",
    unexplainedAnaesthesiaComplications: "⚠ Необясними усложнения по време на анестезия",
    anticipatedDifficultAirway: "⚠ Очакван труден дихателен път",
    difficultAirway: "⚠ Анамнеза за труден дихателен път",
    loadingCase: "Зареждане на резюмето…", loadFailed: "Грешка при зареждане на данните.",
    unfinalizeFailed: "Случаят не може да бъде отворен отново. Опитайте пак.",
  },
}
