import { useLocale } from "next-intl"

// Interface copy only. Drug names, route/unit codes, monitor abbreviations and
// other controlled clinical vocabulary remain sourced from the clinical
// display layer and are intentionally not translated here.
const COPY = {
  en: {
    apply: "Apply",
    confirm: "Confirm",
    discontinue: "Discontinue",
    delete: "Delete",
    discontinueShort: "Disc",
    cancel: "Cancel",
    back: "Back",
    done: "Done",
    other: "Other",
    route: "Route",
    formulation: "Formulation",
    concentration: "Concentration",
    value: "Value",
    dose: "Dose",
    rate: "Rate",
    concentrationPresets: "Concentration presets",
    quickDoses: "Quick doses",
    customConcentrationAria: (unit: string) => `Custom concentration ${unit}`,
    concentrationExample: "e.g. 0.75",
    pagerAria: (label: string, page: number, count: number) => `${label} page ${page} of ${count}`,
    pagerPageAria: (label: string, page: number) => `${label} page ${page}`,
    previousPageAria: (label: string) => `Previous ${label.toLocaleLowerCase()} page`,
    nextPageAria: (label: string) => `Next ${label.toLocaleLowerCase()} page`,
    doubleClickResume: "Double-click to resume",
    infusionBarHelp: "Click to select · Double-click for options · Drag to move",
    removeAria: (name: string) => `Remove ${name}`,
    at: "at",
    editAgent: (name: string) => `Edit: ${name}`,
    startAgent: (name: string) => `Start ${name}`,
    administer: "Administer",
    startInfusion: "Start Infusion",
    totalUsesWeight: (basis: string, weight?: number) => `Total will use ${basis}${weight ? ` ${weight} kg` : " — enter patient weight in preop"}`,
    doseSelectorAria: "Administration route",
    endCase: {
      title: "End Case — Active Items",
      instruction: "Choose what to do with each active item.",
      ready: "No active items — ready to end.",
      continuePostop: "Continue postop",
      estimatedTotal: "Estimated total:",
      calculatedVolume: "Calculated delivered volume. Replace it with the pump total if needed.",
      fullBagQuestion: "Was the full bag infused?",
      fullBagYes: "Yes — full bag",
      partialNo: "No — partial",
      amount: "Amount:",
      gasSettings: "Gas settings",
      incomplete: "Choose an action for every item and confirm each bag amount.",
      confirm: "Confirm End Case",
      actualVolumeAria: (name: string) => `Actual delivered volume for ${name}`,
      partialVolumeAria: (name: string) => `Partial bag volume for ${name}`,
    },
    eventPicker: {
      none: "No events found",
    },
    favourites: {
      reset: "Reset",
      save: "Save",
      saving: "Saving…",
    },
    fluidConflict: {
      conflict: "conflict",
      alreadyRunning: "is already running.",
      stop: (name: string) => `Stop ${name}`,
      runParallel: "Run in parallel",
      fullVolumeQuestion: (category: string) => `Did the full volume of ${category} get infused?`,
      fullyInfused: "Yes, fully infused",
      stoppedEarly: "No, stopped early",
      calculatedVolume: "Calculated delivered volume · edit if needed",
    },
    fluid: {
      entryModeAria: "Fluid entry mode",
      overlappingProfiles: "Multiple clinical fluid profiles apply. Resolve the overlapping rules before using this selector.",
      noneFound: "No fluids found",
      laneKind: "fluid",
      changeRate: "Change fluid rate",
      continueQuestion: "Continue?",
      bag: "Bag",
      rate: "Rate",
      bagVolume: "Bag volume",
      addBag: "Add bag",
      startFluid: "Start fluid",
    },
    gas: {
      carrier: "Carrier gas",
      choose: "choose",
      settings: "Gas Settings",
      tapToStart: "tap to start",
      editSettings: "Edit gas settings",
      startSettings: "Start gas settings",
      start: "Start",
    },
    hotkeys: {
      title: "Keyboard Shortcuts",
      closeAria: "Close keyboard shortcuts",
      rows: [
        ["Click", "Select / deselect item"],
        ["Esc", "Deselect / close dialogs"],
        ["Tab", "Cycle: drugs → infusions → fluids → agents"],
        ["Del / Backspace", "Delete selected item"],
        ["→  (Right arrow)", "Extend bar right / copy drug right"],
        ["←  (Left arrow)", "Retract bar left / remove drug"],
        ["Double-click stopped bar", "Reactivate bar"],
        ["Double-click infusion bar", "Change infusion rate"],
        ["Double-click drug pill", "Change drug dose"],
        ["↑ / ↓", "Adjust vitals slider value"],
        ["Enter", "Confirm value in any input"],
        ["Ctrl + Z", "Undo"],
        ["Ctrl + Y  /  Ctrl + Shift + Z", "Redo"],
      ],
    },
    infusion: {
      discontinued: "discontinued",
      restore: "Restore infusion",
      changeRate: "Change rate",
      laneKind: "infusion",
    },
    premedication: {
      notApplicable: "N/A — not applicable",
      add: "Add —",
      notSet: "Not set — click to add",
    },
    rateChange: {
      title: "Change rate",
      totalsBasis: "Drug totals calculated using",
      pickTime: "Pick time",
      startNow: "Start now",
      missingWeight: " — enter patient weight in preop",
    },
    timetable: {
      caseEndedBadge: "CASE ENDED",
      liveBadge: "LIVE",
      shortcuts: "Shortcuts",
      addHour: "+ 1 hr",
      subtractHour: "- 1 hr",
      total: "Total:",
      resumableUntil: "Resumable until",
      resumeCase: "Resume Case",
      caseEnded: "Case ended",
      endCase: "End Case",
      endNow: "End now",
      writeManually: "Write manually",
      rateSuffix: "rate",
      actualFluidVolumeAria: "Actual delivered fluid volume",
      fullBagYes: "Yes · full bag",
      partialNo: "No · partial",
      partialBagVolumeAria: "Partial bag volume",
      confirmDiscontinue: "Confirm Discontinue",
      hideChart: "Hide chart",
      showChart: "Show chart",
      ongoing: "Ongoing",
      bagSuffix: (volume: number) => `${volume} mL bag`,
    },
  },
  bg: {
    apply: "Приложи",
    confirm: "Потвърди",
    discontinue: "Прекрати",
    delete: "Изтрий",
    discontinueShort: "Прекр.",
    cancel: "Отказ",
    back: "Назад",
    done: "Готово",
    other: "Друго",
    route: "Път на приложение",
    formulation: "Лекарствена форма",
    concentration: "Концентрация",
    value: "Стойност",
    dose: "Доза",
    rate: "Скорост",
    concentrationPresets: "Предварително зададени концентрации",
    quickDoses: "Бързи дози",
    customConcentrationAria: (unit: string) => `Персонализирана концентрация ${unit}`,
    concentrationExample: "напр. 0,75",
    pagerAria: (label: string, page: number, count: number) => `${label}, страница ${page} от ${count}`,
    pagerPageAria: (label: string, page: number) => `${label}, страница ${page}`,
    previousPageAria: (label: string) => `Предишна страница: ${label.toLocaleLowerCase()}`,
    nextPageAria: (label: string) => `Следваща страница: ${label.toLocaleLowerCase()}`,
    doubleClickResume: "Двойно натискане за възстановяване",
    infusionBarHelp: "Натиснете за избор · Двойно натиснете за опции · Плъзнете за преместване",
    removeAria: (name: string) => `Премахни ${name}`,
    at: "в",
    editAgent: (name: string) => `Редактиране: ${name}`,
    startAgent: (name: string) => `Започни ${name}`,
    administer: "Приложи",
    startInfusion: "Започни инфузията",
    totalUsesWeight: (basis: string, weight?: number) => `Общото количество ще използва ${basis}${weight ? ` ${weight} kg` : " — въведете теглото на пациента в предоперативната форма"}`,
    doseSelectorAria: "Път на приложение",
    endCase: {
      title: "Приключване на случая — активни елементи",
      instruction: "Изберете действие за всеки активен елемент.",
      ready: "Няма активни елементи — случаят може да бъде приключен.",
      continuePostop: "Продължи следоперативно",
      estimatedTotal: "Очаквано общо количество:",
      calculatedVolume: "Изчислен влят обем. При нужда го заменете с отчетения от помпата.",
      fullBagQuestion: "Целият сак ли беше влят?",
      fullBagYes: "Да — целият сак",
      partialNo: "Не — частично",
      amount: "Количество:",
      gasSettings: "Настройки на газовете",
      incomplete: "Изберете действие за всеки елемент и потвърдете количеството от всеки сак.",
      confirm: "Потвърди приключването",
      actualVolumeAria: (name: string) => `Действително влят обем за ${name}`,
      partialVolumeAria: (name: string) => `Частичен обем от сака за ${name}`,
    },
    eventPicker: {
      none: "Няма намерени събития",
    },
    favourites: {
      reset: "Нулирай",
      save: "Запази",
      saving: "Запазване…",
    },
    fluidConflict: {
      conflict: "конфликт",
      alreadyRunning: "вече се влива.",
      stop: (name: string) => `Спри ${name}`,
      runParallel: "Вливай паралелно",
      fullVolumeQuestion: (category: string) => `Вля ли се целият обем от ${category}?`,
      fullyInfused: "Да, влят изцяло",
      stoppedEarly: "Не, спрян по-рано",
      calculatedVolume: "Изчислен влят обем · редактирайте при нужда",
    },
    fluid: {
      entryModeAria: "Режим за въвеждане на течност",
      overlappingProfiles: "Приложими са няколко клинични профила за течности. Разрешете припокриващите се правила, преди да използвате този избор.",
      noneFound: "Няма намерени течности",
      laneKind: "течност",
      changeRate: "Промени скоростта на течността",
      continueQuestion: "Да продължи ли?",
      bag: "Сак",
      rate: "Скорост",
      bagVolume: "Обем на сака",
      addBag: "Добави сак",
      startFluid: "Започни течността",
    },
    gas: {
      carrier: "Носещ газ",
      choose: "избери",
      settings: "Настройки на газовете",
      tapToStart: "натиснете за начало",
      editSettings: "Редактиране на настройките на газовете",
      startSettings: "Започване на газовете",
      start: "Започни",
    },
    hotkeys: {
      title: "Клавишни комбинации",
      closeAria: "Затвори клавишните комбинации",
      rows: [
        ["Натискане", "Избиране / отмяна на избора"],
        ["Esc", "Отмяна на избора / затваряне на диалог"],
        ["Tab", "Последователно: медикаменти → инфузии → течности → агенти"],
        ["Del / Backspace", "Изтриване на избрания елемент"],
        ["→  (стрелка надясно)", "Удължаване на лентата / копиране на медикамента надясно"],
        ["←  (стрелка наляво)", "Скъсяване на лентата / премахване на медикамента"],
        ["Двойно натискане върху спряна лента", "Повторно активиране на лентата"],
        ["Двойно натискане върху лента на инфузия", "Промяна на скоростта на инфузията"],
        ["Двойно натискане върху доза", "Промяна на дозата"],
        ["↑ / ↓", "Промяна на стойността на жизнения показател"],
        ["Enter", "Потвърждаване на стойността във всяко поле"],
        ["Ctrl + Z", "Отмяна"],
        ["Ctrl + Y  /  Ctrl + Shift + Z", "Повтаряне"],
      ],
    },
    infusion: {
      discontinued: "прекратена",
      restore: "Възстанови инфузията",
      changeRate: "Промени скоростта",
      laneKind: "инфузия",
    },
    premedication: {
      notApplicable: "Н/П — неприложимо",
      add: "Добави —",
      notSet: "Не е зададено — натиснете за добавяне",
    },
    rateChange: {
      title: "Промяна на скоростта",
      totalsBasis: "Общото количество на медикамента е изчислено спрямо",
      pickTime: "Избери час",
      startNow: "Започни сега",
      missingWeight: " — въведете теглото на пациента в предоперативната форма",
    },
    timetable: {
      caseEndedBadge: "ПРИКЛЮЧЕН СЛУЧАЙ",
      liveBadge: "НА ЖИВО",
      shortcuts: "Клавишни комбинации",
      addHour: "+ 1 ч.",
      subtractHour: "- 1 ч.",
      total: "Общо:",
      resumableUntil: "Може да бъде възобновен до",
      resumeCase: "Възобнови случая",
      caseEnded: "Случаят е приключен",
      endCase: "Приключи случая",
      endNow: "Приключи сега",
      writeManually: "Въведи ръчно",
      rateSuffix: "скорост",
      actualFluidVolumeAria: "Действително влят обем течност",
      fullBagYes: "Да · целият сак",
      partialNo: "Не · частично",
      partialBagVolumeAria: "Частичен обем от сака",
      confirmDiscontinue: "Потвърди прекратяването",
      hideChart: "Скрий графиката",
      showChart: "Покажи графиката",
      ongoing: "Продължава",
      bagSuffix: (volume: number) => `сак ${volume} mL`,
    },
  },
} as const

export type IntraopUiCopy = typeof COPY.en | typeof COPY.bg

export function intraopUiCopy(locale: string): IntraopUiCopy {
  return locale.toLowerCase().startsWith("bg") ? COPY.bg : COPY.en
}

export function useIntraopUiCopy(): IntraopUiCopy {
  return intraopUiCopy(useLocale())
}
