// GENERATED by hisbg-nomenclatures/export-hospital-tables.cjs — do not edit.
//
// NHIS administration routes and the LOSPOR route each arrives as. CL013 is the
// NHIS list of EDQM route terms (keys 1-81), CL046 the HL7 route codes NHIS uses
// for how a drug entered the body. Confirmed by the maintainer on 14 Sep 2026.
// A route not listed has no LOSPOR equivalent and keeps the hospital's label.

export const NHIS_CL013_ROUTES: Readonly<Record<string, string>> = {
  "1": "TOPICAL",
  "2": "BUCCAL",
  "3": "TOPICAL",
  "7": "ENDOTRACHEAL",
  "8": "EPIDURAL",
  "9": "TOPICAL",
  "12": "ENTERAL",
  "13": "ENTERAL",
  "17": "INFILTRATION",
  "18": "INHALATION",
  "19": "ENTERAL",
  "41": "IM",
  "43": "INTRAOSSEOUS",
  "51": "INTRATHECAL",
  "54": "IV",
  "59": "IN",
  "60": "TOPICAL",
  "61": "PO",
  "62": "BUCCAL",
  "64": "INFILTRATION",
  "65": "PERINEURAL",
  "70": "PR",
  "71": "PERINEURAL",
  "75": "SC",
  "76": "SL",
  "79": "TRANSDERMAL"
}

export const NHIS_CL046_ROUTES: Readonly<Record<string, string>> = {
  "IM": "IM",
  "IVINJ": "IV",
  "NASINHLC": "INHALATION",
  "PO": "PO",
  "SQ": "SC",
  "TRNSDERM": "TRANSDERMAL"
}
