/**
 * Generates the offline clinical vocabulary bundled into the mobile app.
 *
 * Diagnosis and procedure search were network-only, so with no connection the
 * pickers returned an empty list — indistinguishable from "no such code" — and
 * a case documented offline could not be finalised because core's clinical
 * validation requires a diagnosis. This emits the vocabulary into
 * `@lospor/core/vocabulary` so the phone can search it with no network.
 *
 * Run from lospor-api with the target database configured:
 *   npx tsx scripts/generate-vocabulary.mts
 *
 * The output is committed. Re-run it when the ICD-10 table or pcs.json changes,
 * and bump VOCABULARY_VERSION so cases record which copy coded them.
 */
import fs from "node:fs"
import path from "node:path"
import { PrismaPg } from "@prisma/adapter-pg"
import { PrismaClient } from "../src/generated/prisma/client"

const VOCABULARY_VERSION = "2026-08-06"
const CORE_VOCABULARY_DIR = path.resolve("../lospor-core/src/vocabulary")

type PcsEntry = { code: string; description: string; group: string; domain: string }

const header = (what: string) => `// GENERATED by lospor-api/scripts/generate-vocabulary.mts — do not edit.
// ${what}
// Vocabulary version: ${VOCABULARY_VERSION}
`

async function icd10(prisma: PrismaClient): Promise<string> {
  // Ordered by code so the per-group caps select the same rows the API's
  // `orderBy: { code: "asc" }` queries do.
  const rows = await prisma.icd10Code.findMany({
    select: { code: true, labelEn: true, labelBg: true },
    orderBy: { code: "asc" },
  })

  const tuples = rows.map(r => JSON.stringify([r.code, r.labelEn, r.labelBg ?? ""]))
  return `${header(`${rows.length} ICD-10 codes (EN + BG).`)}
import type { Icd10SearchRow } from "../search"

/**
 * Stored as tuples rather than objects: the same data as ~30% fewer bytes of
 * source, which matters for a module Hermes has to parse on the phone.
 */
const ROWS: [string, string, string][] = [
${tuples.map(t => `  ${t},`).join("\n")}
]

let expanded: Icd10SearchRow[] | null = null

/** Expanded on first use — never at module load, which would cost app startup. */
export function icd10Rows(): Icd10SearchRow[] {
  if (!expanded) {
    expanded = ROWS.map(([code, labelEn, labelBg]) => ({
      code,
      labelEn,
      ...(labelBg ? { labelBg } : {}),
    }))
  }
  return expanded
}

export const ICD10_ROW_COUNT = ${rows.length}
`
}

function procedures(): string {
  const file = path.join(process.cwd(), "src", "data", "pcs.json")
  const data = JSON.parse(fs.readFileSync(file, "utf8")) as PcsEntry[]

  // One representative per group, first in file order — which is exactly the
  // tie-break the API's scorer applies when no code matches the query.
  const byGroup = new Map<string, { entry: PcsEntry; words: Set<string> }>()
  for (const entry of data) {
    const key = entry.group.toLowerCase().trim()
    let group = byGroup.get(key)
    if (!group) {
      group = { entry, words: new Set<string>() }
      byGroup.set(key, group)
    }
    // Keep every word from every sibling description so the group stays
    // reachable by the wording of codes the reduced set drops.
    for (const word of entry.description.toLowerCase().split(/[^a-z0-9]+/)) {
      if (word.length > 2) group.words.add(word)
    }
  }
  const rows = [...byGroup.values()].sort((a, b) => a.entry.group.localeCompare(b.entry.group))
  const tuples = rows.map(({ entry, words }) => JSON.stringify([
    entry.code, entry.group, entry.domain, entry.description,
    [...words].sort().join(" "),
  ]))

  return `${header(
    `${rows.length} procedure groups, reduced from ${data.length} PCS rows.`,
  )}
import type { ProcedureSearchRow } from "../search"

/**
 * The search endpoint only ever returns one row per group, so the offline copy
 * stores one row per group — 82,121 PCS rows reduce to ${rows.length}.
 *
 * Each row carries every distinct word from every description in its group, so
 * a group stays reachable by the wording of the codes the reduction drops.
 * Single-word queries therefore match as they do online; a multi-word phrase
 * may not, because the words are stored deduplicated rather than in order.
 */
const ROWS: [string, string, string, string, string][] = [
${tuples.map(t => `  ${t},`).join("\n")}
]

let expanded: ProcedureSearchRow[] | null = null

export function procedureRows(): ProcedureSearchRow[] {
  if (!expanded) {
    expanded = ROWS.map(([code, group, domain, description, terms]) => ({
      code, group, domain, description, terms,
    }))
  }
  return expanded
}

export const PROCEDURE_ROW_COUNT = ${rows.length}
`
}

function index(): string {
  return `${header("Offline clinical vocabulary entry point.")}
export { icd10Rows, ICD10_ROW_COUNT } from "./icd10"
export { procedureRows, PROCEDURE_ROW_COUNT } from "./procedures"

/**
 * Stamped onto diagnoses and procedures chosen from the offline copy, so a case
 * coded against a stale vocabulary can be found later. Nothing on the write
 * path validates codes against the server table — PreopDiagnosis.code is a
 * plain string with no foreign key — so drift is silent without this.
 */
export const VOCABULARY_VERSION = "${VOCABULARY_VERSION}"
`
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
})

fs.mkdirSync(CORE_VOCABULARY_DIR, { recursive: true })
fs.writeFileSync(path.join(CORE_VOCABULARY_DIR, "icd10.ts"), await icd10(prisma), "utf8")
fs.writeFileSync(path.join(CORE_VOCABULARY_DIR, "procedures.ts"), procedures(), "utf8")
fs.writeFileSync(path.join(CORE_VOCABULARY_DIR, "index.ts"), index(), "utf8")

for (const name of ["icd10.ts", "procedures.ts", "index.ts"]) {
  const bytes = fs.statSync(path.join(CORE_VOCABULARY_DIR, name)).size
  console.log(`${name.padEnd(16)} ${(bytes / 1024).toFixed(0)} KB`)
}

await prisma.$disconnect()
