import { useLocale } from "next-intl"

// Only the form chrome is translated. Unit codes, route codes, weight bases
// (TBW/IBW), entry modes and formulation values stay international, matching the
// clinical display layer's bgSource policy.
const COPY = {
  en: {
    fluidEntry: "Fluid entry",
    includedEntryModes: "Included entry modes",
    includedFluidEntryModes: "Included fluid entry modes",
    defaultFluidEntry: "Default fluid entry",
    rateAutofill: "Rate autofill calculation",
    none: "None",
    addIncludedRoute: "Add an included route",
    selectRoute: "Select route",
    copySurfaceFrom: "Copy the complete surface from",
    addRoute: "Add route",
    includedRoutes: "Included routes",
    makeDefault: "Make default",
    removeRoute: "Remove route",
    inheritedNote: "Inherited from the legacy base surface. The first change creates route-specific settings.",
    doseSettings: (route: string) => `${route} dose settings`,
    entryMode: "Entry mode",
    amountUnit: "Amount unit",
    bodyUnit: "Body unit",
    timeUnit: "Time unit",
    sliderMin: "Slider minimum",
    sliderMax: "Slider maximum",
    sliderStep: "Slider step",
    sliderRounding: "Slider rounding",
    quickDosePills: (unit: string) => `Quick-dose pills (comma separated, in ${unit})`,
    autofillCalculation: "Autofill calculation",
    calculation: "Calculation",
    manualOnly: "Manual only",
    perKg: "Per kg",
    perM2: "Per m2",
    flatAmount: "Flat amount",
    calculationAmount: "Calculation amount",
    weightBasis: "Weight basis",
    autofillRoundTo: "Autofill round to",
    autofillCap: "Autofill cap",
    capAtActualWeight: "Apply cap at actual weight",
    concentrationSection: "Concentration and formulation pills",
    concentrationUnit: "Concentration unit",
    concentrationPills: "Concentration pills (comma separated)",
    preselectedConcentration: "Preselected concentration",
    suggestedConcentration: "Suggested concentration",
    formulationPills: "Formulation pills",
    preselectedFormulation: "Preselected formulation",
    volumeSection: "Volume, rate and preparation",
    suggestedVolume: "Suggested volume (mL)",
    suggestedRate: "Suggested rate",
    prepAmount: "Preparation strength amount (mg)",
    prepVolume: "Preparation strength volume (mL)",
    advancedProfile: "Advanced profile (read only)",
    rateSliderNote: "Rate slider is fixed at 1–200 mL/h in the clinical selector (step 1). Higher values remain available through manual numeric entry.",
    incompleteRoute: "This route has no complete dose surface. Copy a complete route surface before saving.",
  },
  bg: {
    fluidEntry: "Въвеждане на течности",
    includedEntryModes: "Включени режими на въвеждане",
    includedFluidEntryModes: "Включени режими за течности",
    defaultFluidEntry: "Режим по подразбиране",
    rateAutofill: "Изчисление на скоростта",
    none: "Няма",
    addIncludedRoute: "Добави път на въвеждане",
    selectRoute: "Избери път",
    copySurfaceFrom: "Копирай настройките от",
    addRoute: "Добави път",
    includedRoutes: "Включени пътища",
    makeDefault: "Направи по подразбиране",
    removeRoute: "Премахни пътя",
    inheritedNote: "Наследено от базовия профил. Първата промяна създава настройки за конкретния път.",
    doseSettings: (route: string) => `Настройки за дозиране — ${route}`,
    entryMode: "Режим на въвеждане",
    amountUnit: "Единица за количество",
    bodyUnit: "Телесна единица",
    timeUnit: "Единица за време",
    sliderMin: "Минимум на плъзгача",
    sliderMax: "Максимум на плъзгача",
    sliderStep: "Стъпка на плъзгача",
    sliderRounding: "Закръгляне на плъзгача",
    quickDosePills: (unit: string) => `Бързи дози (разделени със запетая, в ${unit})`,
    autofillCalculation: "Автоматично изчисление",
    calculation: "Изчисление",
    manualOnly: "Само ръчно",
    perKg: "На kg",
    perM2: "На m²",
    flatAmount: "Фиксирана доза",
    calculationAmount: "Стойност за изчисление",
    weightBasis: "Основа за теглото",
    autofillRoundTo: "Закръгляне на автоматичната доза",
    autofillCap: "Горна граница на автоматичната доза",
    capAtActualWeight: "Прилагай границата спрямо действителното тегло",
    concentrationSection: "Концентрации и лекарствени форми",
    concentrationUnit: "Единица за концентрация",
    concentrationPills: "Концентрации (разделени със запетая)",
    preselectedConcentration: "Предварително избрана концентрация",
    suggestedConcentration: "Предложена концентрация",
    formulationPills: "Лекарствени форми",
    preselectedFormulation: "Предварително избрана форма",
    volumeSection: "Обем, скорост и приготвяне",
    suggestedVolume: "Предложен обем (mL)",
    suggestedRate: "Предложена скорост",
    prepAmount: "Количество в приготвения разтвор (mg)",
    prepVolume: "Обем на приготвения разтвор (mL)",
    advancedProfile: "Разширен профил (само за четене)",
    rateSliderNote: "Плъзгачът за скорост в клиничния избор е фиксиран на 1–200 mL/h (стъпка 1). По-високи стойности могат да бъдат въведени ръчно.",
    incompleteRoute: "За този път няма пълна дозова конфигурация. Копирайте пълна конфигурация за пътя, преди да запазите.",
  },
} as const

export function useDoseProfileCopy() {
  const locale = useLocale()
  return locale.startsWith("bg") ? COPY.bg : COPY.en
}
