// Only surrounding UI prose is localized. Clinical codes and standardized
// medical terminology remain unchanged in the rules workbench.
export const CLINICAL_RULES_PAGE_COPY = {
  en: {
    title: "Clinical rulesets",
    subtitle: "Adult and pediatric rules resolve personal, then institution, then platform.",
    adult: "Adult",
    pediatric: "Pediatric",
    current: "Current ruleset",
    noCurrent: "No ruleset is selected for this mode.",
    platform: "Platform",
    institution: "Institution",
    personal: "Personal",
    rulesets: "Available rulesets",
    rules: "Rules",
    createCopy: "Create copy",
    createEditableCopy: "Create an editable copy",
    createDraft: "Create draft",
    name: "Ruleset name",
    key: "Ruleset key",
    description: "Description",
    scope: "Scope",
    source: "Copy from",
    empty: "Start empty",
    publish: "Publish",
    use: "Use this ruleset",
    stopUsing: "Use inherited rules",
    addRule: "Add rule",
    addDrug: "Add drug",
    addFluidInfusion: "Add fluid/infusion",
    search: "Search rules",
    noRules: "No matching rules.",
    draft: "Draft",
    published: "Published",
    retired: "Retired",
    immutable: "Published rulesets are read-only. Create a copy to change them.",
    loading: "Loading clinical rules...",
    retry: "Retry",
    actionFailed: "Clinical rules action failed.",
    deleteConfirm: "Delete this draft rule?",
    editingContext: "Editing context",
    globalContext: "Global · All institutions",
    personalContext: "My personal",
    inherited: "Inherited read-only",
    sourceLabel: "Source",
    edit: "Edit",
    delete: "Delete",
    bandCount: (count: number) => `${count} band(s)`,
    editAria: (label: string) => `Edit ${label}`,
    deleteAria: (label: string) => `Delete ${label}`,
  },
  bg: {
    title: "Клинични набори от правила",
    subtitle: "Правилата се прилагат в ред: лични, институционални, платформени.",
    adult: "Възрастни",
    pediatric: "Педиатрични",
    current: "Текущ набор",
    noCurrent: "Няма избран набор за този режим.",
    platform: "Платформен",
    institution: "Институционален",
    personal: "Личен",
    rulesets: "Достъпни набори",
    rules: "Правила",
    createCopy: "Създай копие",
    createEditableCopy: "Създай копие за редакция",
    createDraft: "Създай чернова",
    name: "Име на набора",
    key: "Код на набора",
    description: "Описание",
    scope: "Обхват",
    source: "Копирай от",
    empty: "Започни с празен набор",
    publish: "Публикувай",
    use: "Използвай този набор",
    stopUsing: "Използвай наследените правила",
    addRule: "Добави правило",
    addDrug: "Добави медикамент",
    addFluidInfusion: "Добави течност/инфузия",
    search: "Търси правила",
    noRules: "Няма съвпадащи правила.",
    draft: "Чернова",
    published: "Публикуван",
    retired: "Спрян",
    immutable: "Публикуваните набори са само за четене. Създайте копие за промени.",
    loading: "Зареждане на клиничните правила...",
    retry: "Опитай отново",
    actionFailed: "Действието с клиничните правила е неуспешно.",
    deleteConfirm: "Да се изтрие ли това правило от черновата?",
    editingContext: "Контекст за редакция",
    globalContext: "Глобално · Всички институции",
    personalContext: "Мои лични",
    inherited: "Наследен · само за четене",
    sourceLabel: "Източник",
    edit: "Редактирай",
    delete: "Изтрий",
    bandCount: (count: number) => `${count} възрастово-тегловни групи`,
    editAria: (label: string) => `Редактирай ${label}`,
    deleteAria: (label: string) => `Изтрий ${label}`,
  },
} as const
